language: java
sudo: false
jdk:
  - openjdk7
  - oraclejdk8
env:
  - PROFILE=exec-jar
  - PROFILE=exec-jar,saml
  - PROFILE=war

# Cache local Maven repository, but exclude our artifacts.
cache:
  directories:
    - $HOME/.m2
    - $HOME/.embedmongo

# Travis provides older Maven 3.2.5 that contains some bug causing incorrect
# dependency resolution when using profiles and alternative dependency types.
before_install:
  - script/travis-install-maven 3.3.1

# Just resolve and install dependencies, don't build or run tests.
install:
  - mvn dependency:go-offline -P $PROFILE --fail-never --threads 5 -B

# Remove local artifacts of ours from any previous build, just to be sure.
before_script:
  - rm -Rf $HOME/.m2/repository/cz/cvut/zuul

# Run unit and integration tests.
# Also install artifacts to the local repo to be available for after_success task.
script:
  - mvn install verify -P $PROFILE -B

# Analyze code coverage and report it to Coveralls.
after_success:
  - script/travis-code-coverage
