sudo: false

language: java
jdk:
  - openjdk7
  - oraclejdk8
addons:
  postgresql: "9.4"
services:
  - postgresql
env:
  - PROFILE=exec-jar
  - PROFILE=exec-jar,saml
  - PROFILE=war

# Cache local Maven repository, but exclude our artifacts.
cache:
  directories:
    - $HOME/.m2
before_cache:
  - rm -Rf $HOME/.m2/repository/cz/cvut/zuul

# Travis provides older Maven 3.2.5 that contains some bug causing incorrect
# dependency resolution when using profiles and alternative dependency types.
before_install:
  - script/travis-install-maven 3.3.9
install:
  - mvn clean install -P $PROFILE -DskipTests=true --batch-mode
before_script:
  - psql -U postgres -c 'create database zuul_oaas_test;'
script:
  - mvn verify -P $PROFILE --batch-mode
after_success:
  - script/travis-code-coverage
